refactor: use pkg_find_opt_dir()

diff --git a/scripts/movit b/scripts/movit
--- a/scripts/movit
+++ b/scripts/movit
@@ -2,18 +2,19 @@
 
 PkgHome="https://movit.sesse.net/"
 
-# REQ: googletest (/usr/src/googletest-*)
+# REQ: $OrigSrcDir/googletest-* [/usr/src/googletest-*]
 
 pkg_pre_configure() {
     local dir
 
     # Makefile: GTEST_DIR ?= /usr/src/gtest
     #dir=$(pkg_last_dir /usr/src 'googletest-[0-9]*')
-    dir=$(find "$Pwd" -mindepth 1 -maxdepth 1 -type d -name 'googletest-[0-9]*' |
-            grep -v -e '-INSTALL$' -e '-BUILD$' | head -1)
-    if [[ ! -d $dir ]]; then
-        echo "dir not found: $Pwd/googletest-[0-9]*"
-        return 1
-    fi
+    #dir=$(find "$Pwd" -mindepth 1 -maxdepth 1 -type d -name 'googletest-[0-9]*' |
+    #        grep -v -e '-INSTALL$' -e '-BUILD$' | head -1)
+    dir=$(pkg_find_opt_dir googletest) || return 1
+    #if [[ ! -d $dir ]]; then
+    #    echo "dir not found: $Pwd/googletest-[0-9]*"
+    #    return 1
+    #fi
     MakeEnv=(GTEST_DIR="$dir"/googletest)
 }
